server:
  build: ./server
  env_file: .env
  ports:
    - "4000:4000"
  volumes:
    - ./server/data:/app/data
  restart: unless-stopped
  dns:
    - 8.8.8.8
    - 1.1.1.1

web:
  build: ./web
  env_file: .env
  ports:
    - "5173:5173"
  restart: unless-stopped

